### PR TITLE
Add unit tests #26

### PR DESCRIPTION
**Pull request by madaan**
More details: https://github.com/GEM-benchmark/GEM-metrics/blob/unit_tests/tests/README.md

### CODE REVIEW

**Comment by tuetschek** [comment]
Thanks @madaan and sorry for the delay! I think it looks good, just one question – could we use the files in `test_data/` to produce what's in `tests/input.py`? I think it would be nicer to just have these examples in one place... or would that break the tests somehow?

**Comment by madaan** [comment]
Hey @tuetschek, thanks for taking a look! I think it should be possible to keep all the test data in json files (and would be slightly cleaner too). I'll take a crack at it.

**Review by tuetschek — APPROVED** [review]
@madaan Thanks for the update – it looks good to me :-). Are you planning to add something more, or shall we merge it?

**Comment by madaan** [comment]
Thanks @tuetschek! It's ready to merge from my end.

**Pull request merged**
