### PR TITLE
Pass window_size = 100 as a default parameter to MSTTR.compute

### PR DESCRIPTION
**Pull request by madaan**
This avoids repeated hard-coding and allows changing the `window_size` externally for unit tests.

### CODE REVIEW

**Comment by tuetschek** [comment]
@madaan Sorry for the delay. Yeah it definitely makes sense to me to have this as a parameter (@evanmiltenburg might also have an opinion on this). 

Just a question – would it work for you if that was a parameter in the constructor, not for the `compute` method? That would feel cleaner to me (the interface would still be the same for all the metrics).

**Comment by evanmiltenburg** [comment]
I'm fine with this.

Note that the standard MSTTR window in the literature is 100 tokens, but my paper on diversity in image descriptions uses a window of 1000 tokens (I regret this decision, but cannot change it anymore). Good to add as a footnote in our GEM metrics paper that this implementation uses 100, just to make sure people don't make unfair comparisons.

**Comment by madaan** [comment]
@tuetschek You're right, it's much cleaner to add it to the constructor. I've updated the PR. 

Thanks!

**Comment by tuetschek** [comment]
Looks good to me 😊 Thanks!

**Pull request merged**
